name: bhawsar_chemical
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.9+14

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_localization: ^0.2.0 #* Add this line for localization
  #* base
  dio: ^5.7.0
  intl: ^0.19.0

  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  #  connectivity_plus: ^6.0.5

  #* files & images
  file_picker: any
  url_launcher: ^6.3.0
  cached_network_image: any
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  syncfusion_flutter_pdfviewer: ^27.1.51
  pinput: ^5.0.0
  #* locations
  geolocator: any
  location: ^7.0.0
  flutter_widget_from_html: ^0.15.2

  #* icons fonts
  google_fonts: ^6.2.1

  #* state management
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5

  #* tools
  device_info_plus: ^10.1.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  workmanager: ^0.5.2
  upgrader: ^11.2.0
  package_info_plus: ^8.0.2

  #* ui
  fluttertoast: ^8.2.8
  responsive_sizer: ^3.3.1
  lottie: ^3.1.2

  #* push notification
  firebase_core: any
  firebase_messaging: any
  flutter_local_notifications: ^17.2.3
  intl_translation: ^0.20.0
  rename: ^3.0.2
  video_player: ^2.9.2
# flutter_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "assets/ic_launcher.png"
#   adaptive_icon_background: #ffffff
#   adaptive_icon_foreground: #ffffff
#   min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_launcher_icons:
  freezed_annotation:
  json_annotation:
  hive_generator:
  json_serializable:
  build_runner:
  pretty_dio_logger: ^1.3.1
  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  intl_utils: any
  logger: ^2.0.1
  flutter_inappwebview: any

flutter:
  generate: true #* add this line for localization (make true if want to generate localization file automatically on save)
  uses-material-design: true

  #* to add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/

flutter_intl:
  enabled: true
